### ISSUE TITLE
good work

### ISSUE THREAD

**Issue by teomalex** [kurtatwork/KurtAtWork-OpenSea-Auto-Uploader#3]

**Comment by kurtatwork** [comment]
I'm guessing that since you were changed the title from 'TypeError' to 'good work' that you were able to get the script working correctly and uploading your NFTs, correct?

If so, please let me know so that I can feel comfortable with closing these issues. 

Also, if you needed to make changes to the default Json parameters, please let us know what you did that made it work for future reference for others that have similar issues, and also so that i can integrate that info into the repo in a future commit.

let me know if you need any more assistance with anything else, and I'd be happy to hear how the script is working for you.

**Comment by kurtatwork** [comment]
Alright, I'm going to go ahead and mark this issue closed.
